### PR TITLE
Removed the line_size param

### LINKED ISSUE #1: Remove the line_size param.
The line_size (or stride) can always be derived from the width and height in the filter since we're always using BGRA right now.

### PR DESCRIPTION
**Pull request by chrsan**

### CODE REVIEW

**Comment by grusell** [comment]
Just stumbled upon this PR. It could be that it is not relevant in this case, but thought I should point out that the documentation seems to warn against using width to calculate linesize: https://fossies.org/linux/ffmpeg/doc/writing_filters.txt line 210ff .

``` 210 This can be done by accessing frame->data[] and frame->linesize[].  Important
  211 note here: the width does NOT match the linesize. The linesize is always
  212 greater or equal to the width. The padding created should not be changed or
  213 even read. Typically, keep in mind that a previous filter in your chain might
  214 have altered the frame dimension but not the linesize. Imagine a crop filter
  215 that halves the video size: the linesizes won't be changed, just the width.
  216 
  217     <-------------- linesize ------------------------>
  218     +-------------------------------+----------------+ ^
  219     |                               |                | |
  220     |                               |                | |
  221     |           picture             |    padding     | | height
  222     |                               |                | |
  223     |                               |                | |
  224     +-------------------------------+----------------+ v
  225     <----------- width ------------->```

**Comment by chrsan** [comment]
Before this PR we used the line size, but since the line size can be greater than the width it’s not very useful nor accurate. We must draw within the current width, and for BGRA the stride will always be width * 4. The link you provided is indeed correct, but I think you’ve misinterpreted it 😉

**Comment by chrsan** [comment]
@grusell Maybe you’re absolutely correct. Every time I read that paragraph I interpret it differently.

**Comment by chrsan** [comment]
This is not a viable option due to how the line size in FFmpeg works. Hence I'm closing this pull request.

**Pull request closed without merging**
